example_task:
  arm_container:
    image: docker:latest
    additional_containers:
      - name: dockerdaemon
        privileged: true
        image: docker:dind
        ports:
          - 2375
          - 2376
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_TLS_CERTDIR: ""
  env:
    DOCKER_HOST: tcp://localhost:2376
  script:
    - netstat -tulpn
    - docker run ubuntu echo hello
