example_task:
  arm_container:
    image: docker:latest
    additional_containers:
      - name: dockerdaemon
        privileged: true
        image: docker:dind
        command: dockerd
        port: 2375
        env:
          DOCKER_DRIVER: overlay2
  env:
    DOCKER_HOST: tcp://localhost:2375
  script: docker run ubuntu echo hello
