example_task:
  arm_container:
    image: ubuntu:latest
    additional_containers:
      - name: mysql
        image: mysql:latest
        port: 3306
        cpu: 1.0
        memory: 512Mi
        env:
          MYSQL_ROOT_PASSWORD: ""
  script:
    - apt update
    - apt install -y curl net-tools
    - netstat -tulpn
    - curl http://localhost:3306
